name: Probeersel
favicon: null
layout_spectrum: 0.74867
typography_spectrum: 0.6595537066459656
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.25
  lightness: 0.24805995938368142
  saturation: 0.5996751328930259
  rhythmicContrast: 0.8465687895659357
purpose: []
